name: Backup CLA Signatures

on:
  schedule:
    # Runs at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Fetch CLA signatures branch
        run: git fetch origin cla-signatures
        
      - name: Create backup
        run: |
          # Create backup directory
          mkdir -p backups/cla-signatures
          
          # Get signatures from cla-signatures branch
          git show origin/cla-signatures:signatures/version1/cla.json > backups/cla-signatures/cla-$(date +%Y%m).json
          
          # Get signature count for commit message
          COUNT=$(jq '.signedContributors | length' backups/cla-signatures/cla-$(date +%Y%m).json)
          
          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Commit backup
          git add backups/cla-signatures/cla-$(date +%Y%m).json
          git commit -m "Monthly CLA signatures backup - $(date +%B\ %Y) - $COUNT signatures"
          
      - name: Push backup to main
        run: git push origin main
        
      - name: Create backup tag
        run: |
          TAG="cla-backup-$(date +%Y%m)"
          git tag -a "$TAG" -m "CLA signatures backup for $(date +%B\ %Y)"
          git push origin "$TAG"