name: "macOS: Build and Pack"

on:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macos-13

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Start with CQLSH tool
        run: echo ""

      - name: Switch to cqlsh branch
        uses: actions/checkout@v4
        with:
          ref: cqlsh

      - name: Setup Python v3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Build CQLSH v6.0.0
        run: |
          cd "v6.0.0-ACv4.0.7"
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          pip install -r requirements.txt
          export PATH="$PWD/venv/bin:$PATH"
          pyinstaller --noconfirm --clean --onefile --noupx --additional-hooks-dir "$PWD" --hiddenimport concurrent.futures --hiddenimport ast --hiddenimport urllib2 cqlsh.py

      - name: Build CQLSH v6.1.0
        run: |
          cd "v6.1.0-ACv4.1.0"
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          pip install -r requirements.txt
          export PATH="$PWD/venv/bin:$PATH"
          pyinstaller --noconfirm --clean --onefile --noupx --additional-hooks-dir "$PWD" --hiddenimport concurrent.futures --hiddenimport ast --hiddenimport urllib2 cqlsh.py

      - name: Rename artifacts
        run: |
          rm -rf /tmp/CQLSH_ALL
          mkdir -p /tmp/CQLSH_ALL
          mv v6.0.0-ACv4.0.7/dist/cqlsh /tmp/CQLSH_ALL/cqlsh-407
          mv v6.1.0-ACv4.1.0/dist/cqlsh /tmp/CQLSH_ALL/cqlsh-410

      - name: Switch to keys_generator branch
        uses: actions/checkout@v4
        with:
          ref: keys_generator

      - name: Build Keys Generator Tool
        run: |
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          pip install -r requirements.txt
          export PATH="$PWD/venv/bin:$PATH"
          pyinstaller --noconfirm --clean --noupx --onefile keys_generator.py

      - name: Save artifact to be used next
        run: |
          mv dist/*keys_generator* /tmp/CQLSH_ALL

      - name: Start with Axonops Developer Workbench
        run: echo ""

      - name: Switch to main branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Setup Node.js v16.20.2
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Install Axonops Developer Workbench dependencies
        run: |
          npm i

      - name: Move CQLSH to bin folder
        run: |
          mkdir -p main/bin
          mv  -v /tmp/CQLSH_ALL/* main/bin

      - name: Pack Axonops Developer Workbench for macOS
        run: |
          npm run mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: AxonOps-Developer-Workbench-amd64.dmg.zip
          path: dist/axonops-developer-workbench*.dmg
