name: "macOS (ARM): Test"

on:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macOS-ARM

    steps:
      - name: Check the user starting the runner
        shell: bash
        run: python3 --version
