name: "macOS: Build and Pack"

on:
  workflow_dispatch:

jobs:
  macOS:
    runs-on: macos-13

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Switch to ${{ steps.extract_branch.outputs.branch }} branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Setup Python v3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Build CQLSH v6.0.0
        run: |
          cd "cqlsh/v6.0.0-ACv4.0.7"
          ls
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          pip install -r requirements.txt
          export PATH="$PWD/venv/bin:$PATH"
          pyinstaller --noconfirm --clean --noupx --onefile cqlsh.py

      - name: Build CQLSH v6.1.0
        run: |
          cd "cqlsh/v6.1.0-ACv4.1.0"
          ls
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          pip install -r requirements.txt
          export PATH="$PWD/venv/bin:$PATH"
          pyinstaller --noconfirm --clean --noupx --onefile cqlsh.py

      - name: Build Keys Generator Tool
        run: |
          cd keys_generator
          ls
          pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          pip install -r requirements.txt
          export PATH="$PWD/venv/bin:$PATH"
          pyinstaller --noconfirm --clean --noupx --onefile keys_generator.py

      - name: Start with AxonOps Developer Workbench
        run: echo ""

      - name: Setup Node.js v16.20.2
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2

      - name: Install AxonOps Developer Workbench dependencies
        run: |
          npm i

      - name: Move CQLSH to bin folder
        run: |
          mkdir -p main/bin
          mv  -v /tmp/CQLSH_ALL/* main/bin

      - name: Pack Axonops Developer Workbench for macOS
        run: |
          npm run mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: AxonOps-Developer-Workbench-amd64.dmg
          path: dist/*.dmg
