name: SBOM

on:
  push:
    branches:
      - 'bugfix/sbom'

defaults:
  run:
    shell: bash

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20.17.0
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0

      - name: Install AxonOps Developer Workbench dependencies
        run: |
          npm cache clean --force
          npm i

      - name: Generate SBOM 1/2
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom.spdx.json
          root-directory: ${{ github.workspace }}

      - name: Generate SBOM 2/2
        uses: anchore/sbom-action@v0
        with:
          artifact-name: sbom.cyclonedx.json
          root-directory: ${{ github.workspace }}
          format: cyclonedx-json

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: |
            sbom.spdx.json
            sbom.cyclonedx.json
