name: Test signing with AzureSignTool

on:
  push:
    branches:
      - 'test-azure-sign'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: Windows
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Change the package.json version to match the tag
        run: |
          VERSION=$(echo $GITHUB_REF_NAME | sed 's/^v//g')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          sed -i.bak 's/"version": "[^"]*"/"version": "'"$VERSION"'"/' package.json && rm package.json.bak
          rm -f package.json.bak
          mkdir -p dist
          cd dist
          curl -LO https://github.com/axonops/axonops-workbench/releases/download/v1.0.0/AxonOps.Workbench-1.0.0-win-x64.exe


      - name: Build & sign (Azure Key Vault)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          dotnet tool install --no-cache --global AzureSignTool --version 6.0.1
          $exe = "dist/AxonOps.Workbench-1.0.0-win-x64.exe"
          azuresigntool.exe sign `
            -kvu  "https://workbechsigning.vault.azure.net" `
            -kvi  "${{ secrets.AZURE_CLIENT_ID }}" `
            -kvt  "${{ secrets.AZURE_TENANT_ID }}" `
            -kvs  "${{ secrets.AZURE_CLIENT_SECRET }}" `
            -kvc  "${{ secrets.AZURE_KEYVAULT_CERT_NAME }}" `
            -fd   sha256 `
            -tr   http://timestamp.digicert.com `
            -v    "$exe"
