name: Trivy Scan
on:
  push:
    branches:
    - main
    - disable-auto-run
  pull_request:
jobs:
  build:
    name: Trivy Scans
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Run Trivy vulnerability scanner in fs mode
    #   uses: aquasecurity/trivy-action@0.20.0
    #   with:
    #     scan-type: 'fs'
    #     scan-ref: '.'
    #     format: json
    #     severity: 'CRITICAL,HIGH,MEDIUM'
    #     output: 'trivy-results.json'
    #     github-pat: ${{ secrets.GITHUB_TOKEN }}

    - name: Run trivy
      run: |
        curl -LO https://github.com/aquasecurity/trivy/releases/download/v0.55.1/trivy_0.55.1_Linux-64bit.deb
        dpkg -i trivy_0.55.1_Linux-64bit.deb
        trivy fs --format json --output trivy-results.json --severity HIGH,CRITICAL --ignore-unfixed .

    - uses: actions/upload-artifact@v4
      with:
        name: trivy-scan
        path: 'trivy-results.json'

    # # Upload the SARIF file generated in the previous step
    # - name: Upload SARIF results file
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: 'trivy-results.sarif'